name: Release

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-release:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: pydepsync
            asset_name: pydepsync-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: pydepsync.exe
            asset_name: pydepsync-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: pydepsync
            asset_name: pydepsync-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: pydepsync
            asset_name: pydepsync-macos-arm64
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
